import type { GridTypeId } from '../../core/gridEngine';
import type { BuildStep, Concept, GridConcept } from '../concepts';

export const GRID_CONCEPTS_EN: Record<GridTypeId, GridConcept> = {
  manuscript: {
    title: 'Manuscript grid (single block)',
    origin: 'Medieval manuscripts and incunabula. The canon of Villard de Honnecourt and Van de Graaf (rediscovered by Tschichold) defines the text block through the diagonal of the page.',
    concept:
      'A single rectangular block of text within margins. It is the simplest structure: everything depends on the proportions of the text block and the margins. In the classical canon, the text block has the same proportion as the page and the margins follow 1/9 (inner and top) and 2/9 (outer and bottom).',
    whenToUse: ['Books for continuous reading (novels, essays)', 'Reports and letters', 'Long-form article pages on the web'],
    avoid: ['Content with many images or kinds of information', 'Pieces that need several reading entry points'],
    strategies: [
      'Aim for 60–70 characters per line by adjusting the type size, not the text block',
      'Use progressive margins: the spread looks centered when the inner margin is the smallest',
      'Turn on the double page and the diagonals to see the canon close up',
      'Headings and folios can sit outside the text block, in the margins',
    ],
    mistakes: ['Equal margins on every side (the page seems to “fall”)', 'Lines that are too long on wide formats'],
  },
  'manuscript-notes': {
    title: 'Manuscript with notes column',
    origin: 'The tradition of marginal commentary (glosses) and Tschichold’s New Typography, which shifted the text to create functional asymmetry.',
    concept:
      'A wide column for the main text and a narrow column for notes, captions, subheads or metadata. The asymmetry creates hierarchy: main and secondary content become visually distinct without any ornament.',
    whenToUse: ['Academic books and art catalogs', 'Reports with side notes', 'Technical documentation'],
    avoid: ['Very narrow formats, such as mobile, where the notes column becomes unreadable'],
    strategies: [
      'Align notes and captions to the baseline of the passage they refer to',
      'The narrow column can hold “hanging heads”',
      'Use a smaller size in the notes column while keeping the same base leading',
    ],
    mistakes: ['Notes with a different leading, breaking the alignment', 'Using the narrow column for long running text'],
  },
  'book-trade': {
    title: 'Trade book (economical 2:3:4:6 progression)',
    origin: 'The inner : top : outer : bottom progression of 2 : 3 : 4 : 6 comes from the manuscripts measured by Tschichold. Twentieth-century trade books (Penguin, Insel) kept the proportion and reduced the margins to save paper.',
    concept:
      'One column with progressive margins smaller than the canon’s: the text block fills about 60% of the page instead of 44%. The inner margin is still the smallest, because it adds to the neighboring page’s at the gutter, and the bottom is still the largest, so the text block does not “fall”.',
    whenToUse: ['Novels, essays and biographies', 'Pocket books and economy editions', 'Any running-text book with a commercial print run'],
    avoid: ['Art books and luxury editions, which call for generous margins', 'Perfect binding without a spine allowance: the text sinks into the fold'],
    strategies: [
      'Turn on binding under Format: perfect binding adds 3 to 6 mm to the inner margin',
      'Adjust the type size to get 60–70 characters per line, not the text block',
      'Keep the leading locked: openings, subheads and breaks in whole lines',
      'Running heads and folios sit in the margins, outside the text block',
    ],
    mistakes: ['Inner margin equal to the outer: on the spread the text looks pushed away from the fold', 'A text block too large for the format: long, tiring lines'],
  },
  'book-morris': {
    title: 'Morris margins (+20% per margin)',
    origin: 'William Morris, at the Kelmscott Press (1891–1898), wrote in The Ideal Book that the unit of the book is the double-page spread and that each margin should grow about 20% over the previous one: inner, top, outer and bottom.',
    concept:
      'The margins follow the ratio 1 : 1.2 : 1.44 : 1.73. The result is a large, dense, dark text block framed by margins that grow from the inside out and from top to bottom. The spread forms a single block, with the narrow gutter stitching the two text blocks together.',
    whenToUse: ['Private press and bibliophile editions', 'Books with heavy type and decorated initials', 'Studies of proportion and book history'],
    avoid: ['Light, airy texts that call for more white', 'Perfect binding without an allowance: the Morris inner margin is narrow'],
    strategies: [
      'Combine with tight leading and heavy romans for a dark, even page',
      'Use color (red) for initials and headings instead of changing sizes',
      'Always judge the spread: the two text blocks should look like a single block',
    ],
    mistakes: ['Using thin typefaces and generous leading: the text block turns gray and the margins lose their meaning', 'Forgetting the binding: the Morris inner margin was designed for sewn signatures'],
  },
  'book-2col': {
    title: 'Two-column reference book',
    origin: 'The Gutenberg Bible (c. 1455) already used two columns. Dictionaries, encyclopedias and reference works keep the model to fit a lot of text in a small size without long lines.',
    concept:
      'Two equal columns with a wide gutter, 1.5 to 2 lines, so each column reads as a unit. The type size is smaller and the measure stays at 35–45 characters, suited to quick reference.',
    whenToUse: ['Dictionaries, encyclopedias and bibles', 'Anthologies and collected works in a small size', 'Technical books with many short entries'],
    avoid: ['Novels and essays for continuous reading: switching columns interrupts the reading', 'Narrow formats, where columns get fewer than 30 characters'],
    strategies: [
      'A gutter of at least one and a half lines of leading; a thin rule in the gutter is optional',
      'Both columns should end on the same line (balancing) at the end of a section',
      'Entry heads in bold or small caps, run in at the start of the paragraph',
    ],
    mistakes: ['A narrow gutter: the columns merge', 'Columns whose lines are out of register with each other'],
  },
  'col-2': {
    title: '2-column grid',
    origin: 'Bibles and early newspapers; still the standard in scientific publications.',
    concept: 'Two equal columns divide the text block. It is stable and symmetrical but offers few combinations: an element takes one column or two.',
    whenToUse: ['Scientific papers, bibles and dictionaries', 'Simple illustrated books', 'Landscape pages with text and image side by side'],
    avoid: ['Compositions that call for asymmetry or many image sizes'],
    strategies: ['Combine with horizontal divisions (fields) to vary image heights', 'Use the gutter as an axis of symmetry for centered headings'],
    mistakes: ['A gutter that is too narrow: the columns look like a single block'],
  },
  'col-3': {
    title: '3-column grid',
    origin: 'Twentieth-century magazines and newspapers. One of the most versatile grids in editorial design.',
    concept: 'Three columns allow spans of 1, 2 or 3: the 2 + 1 combination creates natural asymmetry (main content + sidebar) and 1 + 1 + 1 creates a regular rhythm.',
    whenToUse: ['Magazines, newsletters and leaflets', 'Landing pages with three benefits', 'Posters with a simple hierarchy'],
    avoid: ['Very small formats, where each column drops below ~35 characters'],
    strategies: ['A headline across 2 columns and text in the 3rd creates asymmetric tension', 'Images across 2 columns with the caption in the 3rd, aligned at the bottom', 'For running text, a column of 40–55 characters works well'],
    mistakes: ['Always using the three columns equally (it gets monotonous)'],
  },
  'col-4': {
    title: '4-column grid',
    origin: 'The standard of Swiss posters and of mobile (Material Design: 4 columns on small screens).',
    concept: 'Four columns divide into halves and quarters: spans of 1, 2, 3 and 4. It is the grid in the reference video: headline across 2–3 columns, image across 4, text in 1–2.',
    whenToUse: ['Posters, covers and opening pages', 'Mobile layouts', 'Magazines with half-page images'],
    avoid: ['Running text in a single narrow column on small formats'],
    strategies: ['3 + 1 spans create elegant asymmetry', 'Divide into rows (fields) as well to get a 4 × n modular grid', 'Cut out and reposition elements, as in the video, to test combinations quickly'],
    mistakes: ['Centering everything and wasting the natural asymmetry of 3 + 1'],
  },
  'col-5': {
    title: '5-column grid (asymmetric)',
    origin: 'The New Typography and museum catalogs. The odd number prevents perfect symmetry.',
    concept: 'Five columns favor 2 + 3 and 1 + 4 divisions: the grid “pushes” the designer toward asymmetric, dynamic compositions.',
    whenToUse: ['Art catalogs and photography books', 'Reports with a side column of highlights', 'Pieces that call for modernity'],
    avoid: ['Narrow formats, where each column becomes tiny'],
    strategies: ['Reserve 1 column for captions and metadata and 4 for content', 'Use 2 + 3 to set image against text'],
    mistakes: ['Forcing a central axis (there is no gutter at the center)'],
  },
  'col-6': {
    title: '6-column grid',
    origin: 'Modern editorial and newspaper design (multiples of 2 and 3).',
    concept: 'Six columns contain the 2- and 3-column grids: spans of 1 to 6, halves, thirds and sixths. A lot of flexibility without losing order.',
    whenToUse: ['Magazines and newspapers', 'Annual reports', 'Content websites'],
    avoid: ['Very small formats (cards, mobile)'],
    strategies: ['Running text in spans of 2 (≈ 3 columns) or 3 (≈ 2 columns)', 'Alternate pages in 3 + 3 and 4 + 2 for rhythm', 'Use an empty column 1 as an active margin'],
    mistakes: ['Using 1-column spans for running text (lines too short)'],
  },
  'col-12': {
    title: '12-column grid',
    origin: 'Screen systems: the 960 Grid System (2008), Bootstrap and Material Design. Also used in large-format newspapers.',
    concept: 'Twelve divides by 1, 2, 3, 4, 6 and 12. Components take spans of 3, 4, 6, 8 or 12. On screens, columns are fluid and gutters are fixed (16–32 px).',
    whenToUse: ['Websites and dashboards', 'Design systems with components', 'Newspapers and complex pieces'],
    avoid: ['Simple pieces, where 12 columns become noise', 'Small formats (use 4 columns on mobile)'],
    strategies: ['Define breakpoints: 12 columns on desktop, 8 on tablet, 4 on mobile', 'Running text in at most 6–8 columns on desktop', 'Use “offset” (empty columns) for asymmetry'],
    mistakes: ['Stretching text across all 12 columns', 'Gutters that are not multiples of 8'],
  },
  'mod-3x3': {
    title: '3 × 3 modular grid',
    origin: 'Simple modular compositions; it appears in Swiss posters and square covers.',
    concept: 'Nine equal modules. Few fields: monumental compositions that read at a glance. The division into thirds is close to photography’s rule of thirds.',
    whenToUse: ['Posters and covers with few elements', 'Square social media posts', 'Record sleeves'],
    avoid: ['Long, varied content'],
    strategies: ['Leave at least 3 modules empty', 'Place the main element on an intersection of the thirds'],
    mistakes: ['Filling every module'],
  },
  'mod-4x6': {
    title: '4 × 6 modular grid (24 fields)',
    origin: 'Josef Müller-Brockmann, Grid Systems in Graphic Design. It is the grid in the reference video.',
    concept:
      'Four columns and six rows: 24 fields. The height of each field is a whole number of text lines and the vertical gutter is one empty line. That way images and text share the same flowlines and the page “locks” into place.',
    whenToUse: ['Posters and covers', 'Magazines and catalogs', 'Any piece that mixes text and image'],
    avoid: ['Continuous-text books (too much structure)'],
    strategies: [
      'Turn on “lock to leading” and watch the bottom margin adjust automatically',
      'Images of 2 × 2, 4 × 2 and 4 × 3 fields create proportional relationships',
      'The headline can take the first row of fields and “hang” from the flowline',
      'Try many variations with ◀ ▶: the grid keeps them all coherent',
    ],
    mistakes: ['Fields whose height is not a multiple of the leading (text misaligns across columns)'],
  },
  'mod-6x8': {
    title: '6 × 8 modular grid (Müller-Brockmann)',
    origin: 'Müller-Brockmann describes grids of 8, 20 and 32 fields for catalogs and complex magazines.',
    concept: 'Many small fields give many combinations. The more fields, the greater the freedom (and the risk of disorder). It is the grid of Neue Grafik and of industrial catalogs.',
    whenToUse: ['Catalogs with many images', 'Complex magazines', 'Identity work with many applications'],
    avoid: ['Small formats', 'Pieces with 2 or 3 elements'],
    strategies: ['Group fields into larger units (2 × 2, 3 × 2) and repeat them', 'Keep few alignment axes even with many fields'],
    mistakes: ['Using each field for a different element (it becomes a mosaic without hierarchy)'],
  },
  hierarchical: {
    title: 'Hierarchical grid',
    origin: 'Web and newspaper design: bands of different heights organized by the importance of the content.',
    concept: 'Columns and rows of unequal sizes defined by the content, not by a repeated unit. A header band, a large highlight, content bands and a footer.',
    whenToUse: ['Home pages and landing pages', 'Newspaper front pages', 'Dashboards'],
    avoid: ['Homogeneous, repetitive content (prefer modular)'],
    strategies: ['Start with the most important content and give it the largest band', 'Keep gutters constant even with unequal bands'],
    mistakes: ['Arbitrary bands with no proportional relationship'],
  },
  golden: {
    title: 'Golden section grid',
    origin: 'The ratio φ ≈ 1.618, studied since Euclid and used by Le Corbusier (Modulor) and in book canons.',
    concept: 'Columns and rows in the ratio 1 : 1.618. The larger part is to the smaller as the whole is to the larger. It produces asymmetries that feel “natural”.',
    whenToUse: ['Covers, posters and identities', 'Layouts with one main and one secondary element'],
    avoid: ['Systems with many identical components'],
    strategies: ['Put the focus on the golden lines (gold guides)', 'Use the golden type scale (1.618) for headlines'],
    mistakes: ['Treating φ as a magic formula: hierarchy and contrast are still needed'],
  },
  thirds: {
    title: 'Rule of thirds',
    origin: 'Painting and photography (John Thomas Smith, 1797). A practical simplification of the golden section.',
    concept: 'Divides the page into 3 × 3. The four intersections are strong points of attention; placing the focus there avoids the rigidity of the center.',
    whenToUse: ['Pieces with a dominant photo', 'Posts, slides and covers', 'Minimalist compositions'],
    avoid: ['Long textual content'],
    strategies: ['Place the headline or the face in the photo on an intersection', 'Leave two thirds empty to create “ma”'],
    mistakes: ['Centering the focus out of habit'],
  },
  fibonacci: {
    title: 'Fibonacci grid',
    origin: 'The sequence 1, 1, 2, 3, 5, 8… whose ratio tends toward φ. Used in late De Stijl, architecture and identities.',
    concept: 'Columns and rows grow along the sequence, creating fields of progressive sizes. Each field is the sum of the two before it: a growing rhythm, like a spiral.',
    whenToUse: ['Abstract compositions and posters', 'Image mosaics', 'Identity work'],
    avoid: ['Long running text in the narrow fields'],
    strategies: ['Put the most important element in the largest field', 'Use the narrow bands for metadata and color'],
    mistakes: ['Filling every narrow field with small text'],
  },
  gerstner: {
    title: 'Gerstner grid (58 units)',
    origin: 'Karl Gerstner, Capital magazine (1962) and Designing Programmes (1964). A “programmable grid”.',
    concept: 'The text block is 58 units wide. With 2-unit gutters it divides exactly into 1, 2, 3, 4, 5 or 6 columns, all overlaid. It is a system that contains many grids.',
    whenToUse: ['Magazines that alternate page types', 'Identity systems', 'Anyone who wants maximum flexibility with order'],
    avoid: ['Beginners who have not yet mastered a simple grid'],
    strategies: ['Look at the dashed guides: each one is a possible division', 'Alternate 2 and 3 columns on the same page while keeping the margins'],
    mistakes: ['Mixing divisions at random on the same page'],
  },
  diagonal: {
    title: 'Diagonal grid (constructivist)',
    origin: 'El Lissitzky, Rodchenko and Russian Constructivism; revived by the New Wave.',
    concept: 'A regular grid, rotated. The structure is still there, but the diagonal introduces movement, tension and a reading direction.',
    whenToUse: ['Event, music and sports posters', 'Experimental covers'],
    avoid: ['Long texts (slanted reading is tiring)', 'Interfaces'],
    strategies: ['Use a rising diagonal (advance) or a falling one (fall)', 'Keep one dominant axis: every element at the same rotation', 'Counter it with a small orthogonal shape to anchor the composition'],
    mistakes: ['Rotating each element at a different angle'],
  },
  eightpt: {
    title: '8pt grid with 4pt baseline',
    origin: 'Digital design systems (Material Design, iOS). Screens at 1×, 1.5×, 2× and 3× divide 8 without fractions.',
    concept: 'Every spacing and dimension is a multiple of 8 (fine adjustments in 4). Combined with 4, 8 or 12 columns, it creates consistency across screens and components.',
    whenToUse: ['Apps and interfaces', 'Design systems', 'Any piece headed for Figma'],
    avoid: ['Books and traditional print (use the leading as the unit)'],
    strategies: ['Set line heights in multiples of 4 (16/24, 20/28, 32/40)', 'Spacing: 4, 8, 16, 24, 32, 48, 64', 'Use the tokens exported in the CSS'],
    mistakes: ['“Almost” multiples (15, 23, 33)'],
  },
};

export const CONCEPTS_EN: Concept[] = [
  { id: 'mancha', term: 'Text block (live area)', def: 'The area of the page occupied by content, bounded by the margins.' },
  { id: 'margens', term: 'Margins', def: 'The space between the text block and the trim. They frame, give breathing room and protect against trimming and binding. Progressive margins: inner < top < outer < bottom.' },
  { id: 'coluna', term: 'Column', def: 'A vertical division of the text block. It sets the measure of the lines of text.' },
  { id: 'calha', term: 'Gutter', def: 'The space between columns or fields. In the classical modular grid, the vertical gutter equals one line of leading.' },
  { id: 'campo', term: 'Field / module', def: 'The unit formed where columns and rows intersect. Its height should be a whole number of text lines.' },
  { id: 'fluxo', term: 'Flowline', def: 'A horizontal alignment that crosses the page and guides the eye; elements “hang” from it.' },
  { id: 'baseline', term: 'Baseline grid', def: 'A horizontal grid at every line of leading. It makes text in neighboring columns line up.' },
  { id: 'entrelinha', term: 'Leading', def: 'The distance between baselines. For running text, 120–145% of the type size.' },
  { id: 'medida', term: 'Measure', def: 'The length of the line. Ideally between 45 and 75 characters, around 66 (Bringhurst).' },
  { id: 'escala', term: 'Type scale', def: 'A sequence of sizes related by a ratio (4:3, 3:2, φ). It creates a harmonious hierarchy.' },
  { id: 'espaco', term: 'White space', def: 'Areas without content. Active when it creates tension in the composition; passive when it is merely left over.' },
  { id: 'hierarquia', term: 'Hierarchy', def: 'The reading order created by size, weight, color, position and space.' },
];

export const BUILD_STEPS_EN: BuildStep[] = [
  { id: 'page', title: '1. The format', text: 'Everything starts with the sheet. The proportion of the format conditions every decision that follows.' },
  { id: 'margins', title: '2. The margins', text: 'The margins define the text block. Generous margins give dignity; the bottom one is usually the largest so the text block does not “fall”.' },
  { id: 'columns', title: '3. The columns', text: 'We divide the text block vertically. The number of columns sets the measure of the text and the possible combinations.' },
  { id: 'gutters', title: '4. The gutters', text: 'Between the columns, the gutters separate the content. In the Swiss method, the gutter equals one line of leading.' },
  { id: 'rows', title: '5. The fields', text: 'We also divide horizontally: the fields (modules) appear, each with a whole number of lines.' },
  { id: 'baseline', title: '6. The baseline', text: 'The baseline grid synchronizes all the text. The fields fit into it; the bottom margin adjusts.' },
  { id: 'elements', title: '7. The elements', text: 'Now the cutouts go onto the page: headline, images and text fit into the fields. Change the combination with ◀ ▶.' },
];
