import type { Overlay } from '../../i18n';
import type { School } from '../schools';

export const SCHOOLS_EN: Record<string, Overlay<School>> = {
  swiss: {
    name: 'Swiss / International Typographic Style',
    era: 'Basel and Zurich, 1950–1970',
    summary:
      'Objectivity, legibility and mathematical order. The modular grid is the backbone of everything; sans-serif type, flush left and unjustified, organizes information into clear hierarchies with plenty of active white space.',
    principles: [
      'Modular grid with fields that are multiples of the leading',
      'Flush-left, ragged-right alignment',
      'Balanced asymmetry: the weight is not at the center',
      'Objective photography instead of illustration',
      'Contrast through scale and weight, not ornament',
      'White space is an active element of the composition',
    ],
    typography: 'Neutral grotesques (Akzidenz-Grotesk, Helvetica, Univers). Here: Inter Tight and Inter.',
    gridAdvice: 'Prefer 4×6 or 6×8 modular grids with a locked baseline. Align every element to the flowlines and leave fields empty.',
    headlines: ['The Grid System', 'Order and Clarity', 'Form Follows Function', 'Konstruktive Grafik', 'Der Film', 'Musica Viva', 'Objective Typography'],
    kickers: ['Ausstellung', 'Kunstgewerbemuseum Zürich', 'Program 1958', 'Issue No. 4'],
    quotes: ['The grid is an aid, not a guarantee.', 'Less is more.', 'Order is the basis of all good form.'],
    references: [
      { title: 'Grid Systems in Graphic Design', author: 'Josef Müller-Brockmann', year: '1981' },
      { title: 'Typographie', author: 'Emil Ruder', year: '1967' },
      { title: 'Neue Grafik (magazine)', author: 'Müller-Brockmann, Lohse, Neuburg, Vivarelli', year: '1958–65' },
      { title: 'Der Film (poster)', author: 'Josef Müller-Brockmann', year: '1960' },
    ],
  },
  bauhaus: {
    era: 'Weimar, Dessau and Berlin, 1919–1933',
    summary:
      'Uniting art, craft and industry. Primary geometric shapes (circle, square, triangle), primary colors, sans-serif type and thick bars that direct the eye. The page is a machine for communication.',
    principles: [
      'Primary shapes paired with primary colors (Kandinsky: yellow triangle, red square, blue circle)',
      'Thick bars and rules as structure and direction',
      'Geometric type, often in lowercase (Bayer: Universal)',
      'Dynamic composition with strong horizontal and vertical axes',
      'Photography and photomontage as a modern language',
    ],
    typography: 'Geometric sans (Futura, Bayer’s Universal). Here: Jost.',
    gridAdvice: '3- or 4-column grids with large fields; use geometric shapes that fill whole modules and bars on the flowline.',
    headlines: ['bauhaus ausstellung', 'art and technology', 'form and color', 'staatliches bauhaus', 'a new unity'],
    kickers: ['weimar 1923', 'dessau', 'typography workshop', 'preliminary course'],
    quotes: ['form follows function', 'art and technology: a new unity'],
    references: [
      { title: 'Bauhaus exhibition poster', author: 'Joost Schmidt', year: '1923' },
      { title: 'Universal (alphabet)', author: 'Herbert Bayer', year: '1925' },
      { title: 'Malerei, Fotografie, Film', author: 'László Moholy-Nagy', year: '1925' },
    ],
  },
  constructivism: {
    name: 'Russian Constructivism',
    era: 'Moscow and Petrograd, 1917–1932',
    summary:
      'Art in the service of revolution and production. Tense diagonals, red and black, condensed type in blocks, photomontage and compositions that seem to be in motion.',
    principles: [
      'Diagonals and rotated axes create energy and movement',
      'Restricted palette: red, black and the paper',
      'Heavy, condensed type, often in capitals',
      'Geometric shapes as agents (Lissitzky’s red wedge)',
      'Overlap and photomontage',
    ],
    typography: 'Heavy condensed grotesques. Here: Oswald and PT Sans.',
    gridAdvice: 'Use the diagonal grid and keep one dominant axis. A rising diagonal (left to right) reads as progress.',
    headlines: ['Books!', 'Beat the Whites with the Red Wedge', 'Construction', 'New World', 'Kino-Glaz'],
    kickers: ['Lengiz 1924', 'Moscow', 'State Publishing House', 'Proletarians'],
    quotes: ['Art is dead, long live the art of the machine.', 'Construct, do not decorate.'],
    references: [
      { title: 'Beat the Whites with the Red Wedge', author: 'El Lissitzky', year: '1919' },
      { title: 'Books (Lengiz poster)', author: 'Alexander Rodchenko', year: '1924' },
      { title: 'Dlia golosa (For the Voice)', author: 'El Lissitzky and Mayakovsky', year: '1923' },
    ],
  },
  destijl: {
    name: 'De Stijl / Neoplasticism',
    era: 'The Netherlands, 1917–1931',
    summary:
      'Universal harmony through pure abstraction: only horizontals, verticals, the three primary colors plus black, white and gray. Asymmetric rectangles separated by thick rules.',
    principles: [
      'Only orthogonal lines (no diagonals in Mondrian’s version)',
      'Pure primary colors in rectangular fields',
      'Thick black rules dividing the plane',
      'Dynamic asymmetry and balance by compensating areas',
      'Lettering built from rectangles',
    ],
    typography: 'Geometric, blocky letters. Here: Archivo Black and Archivo.',
    gridAdvice: 'Fibonacci or golden section grids with unequal fields work well; fill some fields with pure color and use rules in the gutters.',
    headlines: ['De Stijl', 'Composition II', 'Rhythm and Plane', 'Neo-Plasticisme'],
    kickers: ['Leiden 1917', 'Maandblad', 'No. 1'],
    quotes: ['The straight line is the expression of the universal.'],
    references: [
      { title: 'De Stijl magazine (cover)', author: 'Vilmos Huszár', year: '1917' },
      { title: 'Composition with Red, Yellow and Blue', author: 'Piet Mondrian', year: '1930' },
    ],
  },
  newtypo: {
    name: 'New Typography (Tschichold)',
    era: 'Germany, 1925–1935',
    summary:
      'Functional, asymmetric typography: order comes from the content, not from centered tradition. Hierarchy through size and weight, generous space, rules and grotesques. The direct basis of the Swiss Style.',
    principles: [
      'Functional asymmetry instead of the central axis',
      'Sans-serif type as “the letter of our time”',
      'Contrast of size, weight and direction for hierarchy',
      'Standardization: DIN formats (A4, A5)',
      'Rules and dots as typographic signals',
    ],
    typography: 'Grotesques and geometric sans (Futura, Akzidenz). Here: Hanken Grotesk.',
    gridAdvice: 'Manuscript with a notes column or 5 asymmetric columns; text takes the wide columns and metadata the narrow ones.',
    headlines: ['Die neue Typographie', 'Functional Typography', 'Phoebus Palast', 'Elementare Typographie'],
    kickers: ['Berlin 1928', 'Ein Handbuch', 'Bildungsverband'],
    quotes: ['The essence of the new typography is clarity.'],
    references: [
      { title: 'Die neue Typographie', author: 'Jan Tschichold', year: '1928' },
      { title: 'Elementare Typographie', author: 'Jan Tschichold', year: '1925' },
      { title: 'Phoebus Palast posters', author: 'Jan Tschichold', year: '1927' },
    ],
  },
  classical: {
    name: 'Renaissance book (Aldus Manutius)',
    era: 'Venice and Europe, 15th–18th centuries',
    masters: ['Aldus Manutius', 'Claude Garamond', 'Nicolas Jenson', 'Giambattista Bodoni', 'Jan Tschichold (late)'],
    summary:
      'The page as a harmony of proportions. A text block with the same proportion as the page, progressive margins (inner < top < outer < bottom), a central axis, small caps, drop caps and high-contrast romans.',
    principles: [
      'Van de Graaf / Villard canon: 2:3 proportions and 1/9 margins',
      'Progressive margins that balance the spread',
      'Symmetrical axis and centered headings',
      'Humanist or Garalde romans, small caps and italics',
      'Even typographic color: justification with careful hyphenation',
    ],
    typography: 'Garaldes (Garamond, Bembo, Jenson). Here: EB Garamond.',
    gridAdvice: 'Use the manuscript grid with the canon and turn on the double page to see the mirroring. The text block should have the proportion of the page.',
    headlines: ['Hypnerotomachia Poliphili', 'On the Art of Printing', 'Elements of Style', 'Chapter the First'],
    kickers: ['Venetiis MCCCCXCIX', 'Book I', 'In aedibus Aldi'],
    quotes: ['Typography exists to honor content.'],
    references: [
      { title: 'Hypnerotomachia Poliphili', author: 'Aldus Manutius', year: '1499' },
      { title: 'The Form of the Book', author: 'Jan Tschichold', year: '1975' },
      { title: 'The Elements of Typographic Style', author: 'Robert Bringhurst', year: '1992' },
      { title: 'A construção do livro', author: 'Emanuel Araújo', year: '1986' },
    ],
    book: {
      chapter: { label: 'Chapter' },
      recipe: {
        fonts: '1 family, 4 styles: EB Garamond in roman, italic, small caps and letterspaced capitals. Hierarchy comes from case and style, with almost no change of size.',
        margins: 'Van de Graaf canon: 1/9 and 2/9 of the page. The text block has the proportion of the page and fills about 44% of its area.',
        leading: '10.8/14 pt (130%), justified.',
        paragraph: '1 em indent. The first paragraph after a heading or a break starts flush.',
        opening: '1/3 sink, “Chapter I” in red small caps, title in letterspaced capitals, ❦ fleuron, a 3-line red drop cap and the first words in small caps.',
        hierarchy: 'A: letterspaced capitals at text size, centered, 2 lines before and 1 after. B: centered italic, 1 line before. C: small caps run in at the start of the paragraph.',
      },
      masterpieces: [
        { title: 'Hypnerotomachia Poliphili', who: 'Aldus Manutius, type by Francesco Griffo', year: '1499', lesson: 'Text and image composed like architecture. Drop caps and letterspaced capitals build the hierarchy without changing family.' },
        { title: 'De Aetna', who: 'Pietro Bembo, printed by Aldus Manutius', year: '1496', lesson: 'Griffo’s roman, the origin of the Garaldes: even color and calm proportions.' },
        { title: 'The Form of the Book', who: 'Jan Tschichold', year: '1975', lesson: 'Reconstructs the canon of margins of the manuscripts and shows why the text block should have the proportion of the page.' },
      ],
    },
  },
  vignelli: {
    name: 'American Modernism (Vignelli)',
    era: 'New York, 1960–2000',
    summary:
      'Discipline, appropriateness and timelessness. Few typefaces (Helvetica, Bodoni, Garamond, Century, Futura), rigorous grids, black bands and contrast of scale. “If you do it right, it will last forever.”',
    principles: [
      'Semantics, syntactics and pragmatics: meaning, structure and use',
      'A small typographic vocabulary used with mastery',
      'Rigorous grids with a dominant top band (header)',
      'Extreme contrast of scale between headlines and text',
      'Black, white and red as the palette',
    ],
    typography: 'Bodoni for headlines and a grotesque for text. Here: Bodoni Moda and Inter.',
    gridAdvice: 'Hierarchical or 6 columns with a strong top band. Keep the vocabulary minimal and consistent.',
    headlines: ['The Vignelli Canon', 'Timeless', 'Discipline', 'Design is One'],
    kickers: ['New York', 'Unimark International', 'No. 12'],
    quotes: ['If you do it right, it will last forever.', 'Design is one.'],
    references: [
      { title: 'The Vignelli Canon', author: 'Massimo Vignelli', year: '2010' },
      { title: 'NYC Subway Diagram', author: 'Massimo Vignelli', year: '1972' },
      { title: 'American Airlines identity', author: 'Massimo Vignelli', year: '1967' },
    ],
  },
  newwave: {
    name: 'New Wave / Postmodern',
    era: 'Basel, California, London, 1970–1995',
    summary:
      'Questioning Swiss neutrality from within: layers, letterspaced and rotated type, abrupt changes of scale, textures and the deliberate breaking of the grid. The grid exists to be stretched.',
    principles: [
      'The grid is known so it can be broken with intent',
      'Layers, overlaps and transparencies',
      'Exaggerated tracking and scale, rotated words',
      'Vibrant color and controlled noise',
      'Reading as experience, not just transmission',
    ],
    typography: 'Expressive grotesques and display faces. Here: Syne and Space Grotesk.',
    gridAdvice: 'Start from a dense modular grid (6×8) and let 1 or 2 elements escape: rotation, bleed, overlap. Everything else stays aligned.',
    quotes: ['Don’t mistake legibility for communication.'],
    references: [
      { title: 'Ray Gun magazine', author: 'David Carson', year: '1992–95' },
      { title: 'Kunsthalle Basel posters', author: 'Wolfgang Weingart', year: '1977–84' },
      { title: 'Does It Make Sense? (Design Quarterly)', author: 'April Greiman', year: '1986' },
    ],
  },
  japanese: {
    name: 'Japanese minimalism',
    era: 'Tokyo, 1950–present',
    summary:
      '“Ma” (間): the interval, emptiness charged with meaning. Few elements, plenty of breathing room, subtle balance, flat colors and discreet type. Silence communicates as much as form.',
    principles: [
      'Ma: empty space is the protagonist',
      'Few elements placed with precision',
      'Serene asymmetry (no mandatory center)',
      'Flat, natural colors with a single accent',
      'Small type, vertical or pushed to the edges',
    ],
    typography: 'Mincho and Gothic. Here: Noto Serif JP and Noto Sans JP.',
    gridAdvice: 'Thirds or golden section with few elements. Fill less than half of the fields and use the margin as active space.',
    headlines: ['Ma 間', 'Emptiness', 'Muji', 'Silence and Form', 'Nihon Buyo'],
    kickers: ['Tokyo', 'Design Committee', 'Spring'],
    quotes: ['Emptiness holds every possibility.'],
    references: [
      { title: 'Nihon Buyo (poster)', author: 'Ikko Tanaka', year: '1981' },
      { title: 'Designing Design', author: 'Kenya Hara', year: '2007' },
      { title: 'Tokyo Olympics 1964 (poster)', author: 'Yusaku Kamekura', year: '1961' },
    ],
  },
  editorial: {
    name: 'Magazine editorial',
    era: 'New York and London, 1930–present',
    summary:
      'Reading rhythm across the spread: high-contrast serif headlines, bled photography, text in columns, standfirsts and pull quotes. A rich hierarchy with several entry points.',
    principles: [
      'Multiple entry points: headline, subhead, standfirst, caption',
      'Contrast between display serif and text face',
      'Large photography in dialogue with the text (Brodovitch)',
      'Text columns of 45–75 characters',
      'Rhythm and breathing room between pages',
    ],
    typography: 'Didone display and a serif text face. Here: Playfair Display and Source Serif 4.',
    gridAdvice: '3, 6 or 12 columns. Images take multiples of columns; body text in 1 to 2 columns; a pull quote crossing the gutter.',
    headlines: ['The Age of the Grid', 'The Return of Form', 'Interview: The Drawing of Time', 'Invisible Cities'],
    kickers: ['Essay', 'Culture', 'Autumn Issue', 'Profile'],
    quotes: ['“A good page is a conversation between image and text.”', '“Readers come in through the image and stay for the text.”'],
    references: [
      { title: "Harper's Bazaar", author: 'Alexey Brodovitch', year: '1934–58' },
      { title: 'Twen (magazine)', author: 'Willy Fleckhaus', year: '1959–71' },
      { title: 'Interview / Vogue Paris', author: 'Fabien Baron', year: '1980–2000' },
    ],
  },
  webui: {
    name: 'Modern web / UI (8pt, 12 columns)',
    era: 'Digital, 2010–present',
    masters: ['Material Design (Google)', 'Apple HIG', 'Bootstrap', 'Ethan Marcotte (responsive)'],
    summary:
      'Design systems for screens: an 8pt grid, 12 fluid columns, breakpoints, type tokens and reusable components. Legibility at any size and consistency at scale.',
    principles: [
      'Spacing in multiples of 8 (4 for fine adjustments)',
      '12 columns on desktop, 8 on tablet, 4 on mobile',
      'Modular type scale with tokens',
      'Hierarchy through weight, size and accessible contrast (WCAG)',
      'Content first, mobile first',
    ],
    typography: 'Interface grotesques. Here: IBM Plex Sans.',
    gridAdvice: 'Use 12 columns or the 8pt grid. Components take spans of 3, 4, 6 or 12; running text never goes beyond 8 columns.',
    headlines: ['Build faster', 'Your product, at scale', 'Design System 2.0', 'Get started'],
    kickers: ['New', 'Platform', 'Beta', 'Features'],
    quotes: ['Consistency is the best feature.'],
    references: [
      { title: 'Material Design Guidelines', author: 'Google', year: '2014–present' },
      { title: 'Responsive Web Design', author: 'Ethan Marcotte', year: '2010' },
      { title: 'Human Interface Guidelines', author: 'Apple', year: '1987–present' },
    ],
  },
  brutalism: {
    name: 'Web brutalism',
    era: 'Internet, 2014–present',
    summary:
      'Exposed structure, raw and honest: monospaced type, visible borders, default system colors, blocks that reveal the grid instead of hiding it.',
    principles: [
      'The grid is visible: borders, rules and boxes in plain sight',
      'Monospaced and system fonts',
      'Pure system colors (link blue, yellow, black)',
      'Direct, literal hierarchy',
      'Anti-polish as a stance',
    ],
    typography: 'Monospaced. Here: Space Mono.',
    gridAdvice: '8pt grid or 12 columns with visible borders; leave the modules showing and use raw contrast of scale.',
  },
  penguin: {
    name: 'Modern classic (Tschichold / Penguin)',
    era: 'London, 1947–1949',
    masters: ['Jan Tschichold', 'Hans Schmoller', 'Allen Lane (publisher)'],
    summary:
      'The paperback as a work of precision: one family, almost a single size, a central axis, small caps and italic doing all the hierarchy. Written rules so that thousands of titles came out consistent.',
    principles: [
      'One size for almost everything: hierarchy comes from case and style',
      'Central axis and serene symmetry',
      'First words of the chapter in small caps, no drop cap',
      'Section break: one blank line',
      'Economical but progressive margins',
    ],
    typography: 'Garalde and transitional text faces (Bembo, Baskerville, Garamond). Here: Crimson Pro, a single family.',
    gridAdvice: 'Use the trade book grid on a double page, with an allowance for perfect binding. One column, an economical text block.',
    headlines: ['The Drawing of Time', 'The Silent Page'],
    kickers: ['Penguin Modern Classics', 'Part One'],
    quotes: ['Perfect typography is certainly the most elusive of all arts.'],
    book: {
      recipe: {
        fonts: '1 family and practically 1 size: Crimson Pro in roman, italic, small caps and letterspaced capitals.',
        margins: 'Economical 2:3:4:6 progression, typical of the paperback, with a spine allowance for perfect binding.',
        leading: '10.5/13 pt (124%), justified.',
        paragraph: '1 em indent; the first paragraph of the chapter and the one after a break start flush.',
        opening: 'Sink of about 30%, chapter number in slightly larger figures, title in letterspaced capitals at text size and the first words in small caps. No drop cap, no running heads.',
        hierarchy: 'A: letterspaced capitals. B: small caps. C: run-in italic. Three levels at the same size, one variable per level. Fiction does without running heads: the folio at the foot is enough.',
      },
      masterpieces: [
        { title: 'Penguin Composition Rules', who: 'Jan Tschichold', year: '1947', lesson: 'Four pages of rules that standardized indents, letterspacing of capitals, small caps and breaks across the whole list.' },
        { title: 'Penguin Classics and Penguin Shakespeare', who: 'Jan Tschichold, redesign', year: '1947–1949', lesson: 'Hierarchy with a single size: readers feel the order without noticing the styles.' },
      ],
    },
  },
  privatepress: {
    name: 'Private press (Morris / Doves / Gill)',
    era: 'England, 1891–1931',
    summary:
      'The craft reaction to the industrial book: a dense, dark page, margins that grow 20% from one to the next, red initials and pilcrows instead of indents. Hierarchy comes from color (rubrication) and the size of the initial.',
    principles: [
      'The unit is the double-page spread (Morris)',
      'Margins in the ratio 1 : 1.2 : 1.44 : 1.73',
      'Dense text block, tight leading, dark typographic color',
      'Rubrication: initials, headings and signs in red',
      'Continuous paragraphs marked by ¶ (Gill)',
    ],
    typography: 'Heavy Venetian romans (Golden Type, Doves Type). Here: Alegreya at medium weight.',
    gridAdvice: 'Use the Morris grid on a double page. One wide, dense column; the bottom margin is the largest.',
    headlines: ['Memoirs of the Drawing Board', 'The Unfinished Book'],
    kickers: ['Kelmscott', 'Book the First'],
    quotes: ['The unit of the book is not the page but the pair of pages.'],
    book: {
      chapter: { label: 'Chapter' },
      recipe: {
        fonts: '1 family at medium weight: Alegreya for the text, heavy bold for headings and red for everything that organizes.',
        margins: 'Morris: each margin 20% larger than the previous one, from inner to top, outer and bottom (1 : 1.2 : 1.44 : 1.73).',
        leading: '11.6/13.5 pt (116%): dense on purpose, for a dark and even page.',
        paragraph: 'Continuous paragraphs separated by red ¶ pilcrows, without indent and without a new line.',
        opening: 'Minimal sink, chapter number spelled out in red, title in heavy capitals, ❧ fleuron and a 4-line red initial.',
        hierarchy: 'The hierarchy is chromatic: red for headings, initials and signs; black for the text. Size only changes in the initial and in head A.',
      },
      masterpieces: [
        { title: 'Kelmscott Chaucer', who: 'William Morris and Edward Burne-Jones', year: '1896', lesson: 'The spread as a unit, progressive margins and ornament integrated with the text.' },
        { title: 'Doves Bible', who: 'T. J. Cobden-Sanderson and Emery Walker', year: '1903–1905', lesson: 'No ornament: only well-set type and red initials. Proof that hierarchy can come from color.' },
        { title: 'An Essay on Typography', who: 'Eric Gill', year: '1931', lesson: 'Paragraphs marked by ¶ pilcrows within the text block, with no indent and no new line.' },
      ],
    },
  },
  hochuli: {
    name: 'Swiss asymmetric book (Hochuli)',
    era: 'St. Gallen and Zurich, 1930–present',
    masters: ['Jost Hochuli', 'Jan Tschichold (1930s)', 'Max Caflisch', 'Robin Kinross'],
    summary:
      'The modern book without a central axis: text flush left, headings in a grotesque, a wide outer margin for notes and numbers. Order comes from position and alignment, not symmetry.',
    principles: [
      'Functional asymmetry: the axis is the left edge of the text',
      'Flush left, unjustified, with an even rag',
      'Two families with distinct roles: serif for reading, grotesque for orientation',
      'A notes column in the outer margin',
      'Running head and folio together at the top, at the outer corner',
    ],
    typography: 'A serif text face with a grotesque for headings and paratext. Here: Literata and Instrument Sans.',
    gridAdvice: 'Use the manuscript grid with a notes column on a double page: the narrow column sits in the outer margin of each page.',
    headlines: ['A Treatise on Brief Form', 'The Silent Page'],
    quotes: ['Symmetry and asymmetry are choices of function, not of ideology.'],
    references: [
      { title: 'Designing Books: Practice and Theory', author: 'Jost Hochuli and Robin Kinross', year: '1996' },
      { title: 'Detail in Typography', author: 'Jost Hochuli', year: '1987' },
      { title: 'Typographische Gestaltung', author: 'Jan Tschichold', year: '1935' },
    ],
    book: {
      recipe: {
        fonts: '2 families: Literata for the text and Instrument Sans for headings, numbers, running heads and notes. Structural contrast (serif × grotesque) with similar x-heights.',
        margins: 'Asymmetric: a narrow inner margin and a wide outer one that holds the notes column.',
        leading: '10/14 pt (140%): more air because the text is not justified.',
        paragraph: '1 em indent, flush left with a rag and without excessive hyphenation.',
        opening: '1/3 sink, a large red number in the grotesque and a flush-left title. No drop cap, no ornament.',
        hierarchy: 'Numbered headings in a semibold grotesque: A larger and with 2 lines before, B at text size, C run in. Flush-left alignment is constant; only size and space change.',
      },
      masterpieces: [
        { title: 'Edition Typotron and Edition Ostschweiz', who: 'Jost Hochuli', year: '1983–2010', lesson: 'Small books with precise asymmetry: each page resolves the relationship between text, note and image through alignment.' },
        { title: 'Designing Books: Practice and Theory', who: 'Jost Hochuli and Robin Kinross', year: '1996', lesson: 'Argues that symmetry and asymmetry are functional choices, decided by the content.' },
        { title: 'Typographische Gestaltung', who: 'Jan Tschichold', year: '1935', lesson: 'Asymmetric typography applied to the book, before Tschichold returned to the classical.' },
      ],
    },
  },
  contemporary: {
    name: 'Contemporary literature (3 styles)',
    era: 'Brazil and worldwide, 1990–present',
    summary:
      'Today’s fiction and essay book: an expressive display face for openings, a comfortable serif for text and a discreet sans for paratext. The chapter number becomes an image.',
    principles: [
      'Three styles, three roles: display, text and paratext',
      'Openings like small posters; a quiet body',
      'Epigraphs and numbers as graphic elements',
      'Trade margins with a spine allowance',
      'Folios and running heads in the sans, discreet',
    ],
    typography: 'A high-contrast serif display, a serif text face and a small grotesque. Here: Fraunces, Newsreader and Inter.',
    gridAdvice: 'Use the trade book grid on a double page with perfect binding. Openings use the sink as a stage.',
    headlines: ['The Unfinished Book', 'Memoirs of the Drawing Board'],
    kickers: ['Novel', 'Essays'],
    quotes: ['The book designer serves the text.'],
    references: [
      { title: 'On Book Design', author: 'Richard Hendel', year: '1998' },
      { title: 'Book Design', author: 'Andrew Haslam', year: '2006' },
      { title: 'Cosac Naify editions', author: 'art direction by Elaine Ramos', year: '2000–2015' },
    ],
    book: {
      recipe: {
        fonts: '3 styles with fixed roles: Fraunces (display) for openings and A heads, Newsreader for text and B heads, Inter for paratext: running heads, folios, notes and C heads.',
        margins: 'Trade and progressive (economical 2:3:4:6), with an allowance for perfect binding.',
        leading: '10.2/14.5 pt (142%), justified.',
        paragraph: '1 em indent; first paragraph flush, with the first words in small caps.',
        opening: 'A huge orange number as an image, the title in display italic and a right-aligned epigraph.',
        hierarchy: 'Each level switches family: A in the display face, B in the text italic, C in the sans in small capitals. With three families, each needs a single role.',
      },
      masterpieces: [
        { title: 'Cosac Naify editions', who: 'art direction by Elaine Ramos', year: '2000–2015', lesson: 'A design for each title, with graphic openings and a rigorous body: the book as an object.' },
        { title: 'On Book Design', who: 'Richard Hendel', year: '1998', lesson: 'The book designer serves the text: each work calls for its own solution, with no formula.' },
        { title: 'Book Design', who: 'Andrew Haslam', year: '2006', lesson: 'A handbook of book conventions: grids, margins, hierarchy and production.' },
      ],
    },
  },
  technical: {
    name: 'Technical and teaching book (Tufte)',
    era: 'USA and Europe, 1983–present',
    summary:
      'The book that teaches: numbered sections, side notes next to the argument, figures with captions in the margin. A superfamily gives three coherent styles for text, headings and data.',
    principles: [
      'Numbered sections (3, 3.1, 3.1.1) for cross-reference',
      'Notes and captions in the margin, beside the text (Tufte)',
      'Superfamily: serif, sans and mono built on the same skeleton',
      'Flush left with paragraphs separated by space',
      'Figures integrated into the flow of the text',
    ],
    typography: 'The Source superfamily: Source Serif 4 (text), Source Sans 3 (headings) and Source Code Pro (numbers and data).',
    gridAdvice: 'Use the manuscript grid with a notes column: the wide column takes the text, the narrow one takes side notes and captions.',
    headlines: ['A Treatise on Brief Form', 'The Drawing of Time'],
    kickers: ['Handbook', 'Volume 1'],
    quotes: ['Above all else show the data.'],
    references: [
      { title: 'The Visual Display of Quantitative Information', author: 'Edward Tufte', year: '1983' },
      { title: 'Envisioning Information', author: 'Edward Tufte', year: '1990' },
      { title: 'Thinking with Type', author: 'Ellen Lupton', year: '2004' },
    ],
    book: {
      chapter: { label: 'Chapter' },
      recipe: {
        fonts: '3 styles from one superfamily: Source Serif 4 for reading, Source Sans 3 for headings and captions, Source Code Pro for section numbers, folios and data. The shared design guarantees harmony.',
        margins: 'Asymmetric, with a wide notes column in the outer margin for side notes and captions.',
        leading: '9.6/13 pt (135%), flush left.',
        paragraph: 'Paragraphs separated by a blank line, without indent: it favors reference and non-linear reading.',
        opening: '“Chapter 3” label in blue mono, a large title in the sans and a 1/4 sink.',
        hierarchy: 'Decimal numbering (3.1, 3.1.1) in the semibold sans: the number carries the hierarchy and size only confirms it.',
      },
      masterpieces: [
        { title: 'The Visual Display of Quantitative Information', who: 'Edward Tufte', year: '1983', lesson: 'Side notes and figures next to the argument: readers do not have to turn the page to see the evidence.' },
        { title: 'The Elements of Typographic Style', who: 'Robert Bringhurst', year: '1992', lesson: 'Numbered sections and notes in the wide margin: the book itself demonstrates what it teaches.' },
        { title: 'Thinking with Type', who: 'Ellen Lupton', year: '2004', lesson: 'Visual teaching: every rule comes with a typeset example.' },
      ],
    },
  },
};
